export interface Sprite {
  name: string;
  palette: Record<string, string>;
  rows: string[];
}

export interface Pixel {
  x: number;
  y: number;
  c: string;
}

export const SPRITE_PREFIX = 'px:';

const K = '#222222';

// Symmetric sprites are drawn as their left half.
const mirror = (half: string[]) => half.map((row) => row + [...row].reverse().join(''));

const CAP_HERO = [
  '....RRRRR...',
  '...RRRRRRRR.',
  '..RRRRRRRRRR',
  '...HHSSSSSS.',
  '...HSSKSSKS.',
  '...HSSSSSSS.',
  '....SSMMSS..',
  '....SSSSSS..',
  '...BBBBBBBB.',
  '..SBBBWBBBBS',
  '...BBBBBBBB.',
  '...KK....KK.',
];

const BATTLE_TOP = mirror([
  '........',
  '........',
  '......KK',
  '.....KCC',
  '...KKKCG',
  '.KKAAAKC',
  'KAALAAAK',
  'KAAAAAAA',
  '.KMMMMMM',
  '..KMWMMM',
  '...KKDDD',
  '.....KDD',
  '......KD',
  '.......K',
  '....SSSS',
  '........',
]);

const TOP_METAL = { K, M: '#b0bec5', W: '#ffffff', D: '#546e7a', S: '#cfd8dc' };

// Original characters, 12x12 or 16x16. '.' is transparent; other letters map to the palette.
export const SPRITES: Record<string, Sprite> = {
  hero: {
    name: 'Red cap hero',
    palette: { R: '#e53935', H: '#5d4037', S: '#ffcc99', K, M: '#c62828', B: '#1e88e5', W: '#ffffff' },
    rows: CAP_HERO,
  },
  dino: {
    name: 'Green dino',
    palette: { G: '#43a047', D: '#2e7d32', W: '#e8f5e9', K, O: '#fb8c00' },
    rows: [
      '.....GGGGG..',
      '....GGGGGGG.',
      '...GGWKGGGGG',
      '...GGGGGGGGG',
      '..GGGGGGGGGG',
      '..GGKGGGGGGG',
      '...GGGGGGG..',
      '..OGGWWWGG..',
      '.OGGGWWWGGG.',
      '..GGGWWWGGGO',
      '..GGGGGGGGGO',
      '..DD....DD..',
    ],
  },
  sparky: {
    name: 'Sparky',
    palette: { Y: '#fdd835', K, P: '#ef5350', B: '#8d6e63' },
    rows: [
      '..K......K..',
      '..YY....YY..',
      '..YYY..YYY..',
      '..YYYYYYYY..',
      '.YYYYYYYYYY.',
      '.YYKYYYYKYY.',
      '.YPYYYYYYPY.',
      '.YYYYKKYYYY.',
      '..YYYYYYYY..',
      '.YYYYYYYYYYB',
      '.YYBYYYYBYY.',
      '..YY....YY..',
    ],
  },
  ember: {
    name: 'Ember',
    palette: { O: '#fb8c00', C: '#ffe0b2', K, F: '#ffeb3b', R: '#f4511e' },
    rows: [
      '..........F.',
      '.........RFF',
      '....OOOO.RF.',
      '...OOOOOOOO.',
      '...OKOOKOO..',
      '...OOOOOOO..',
      '....OOOOO...',
      '...OCCCCCO..',
      '..OOCCCCCOO.',
      '...OCCCCCO..',
      '...OOOOOOO..',
      '...OO...OO..',
    ],
  },
  shelly: {
    name: 'Shelly',
    palette: { G: '#66bb6a', L: '#1e88e5', l: '#64b5f6', K, W: '#ffffff' },
    rows: [
      '............',
      '.....LLLLL..',
      '....LlLlLLL.',
      '...LlLlLlLLL',
      '...LLLLLLLLL',
      'GG.LlLlLlLLL',
      'GWKLLLLLLLLL',
      'GGGGLlLlLlL.',
      '.GGGLLLLLLL.',
      '....GG..GG..',
      '............',
      '............',
    ],
  },
  mushroom: {
    name: 'Mushroom',
    palette: { R: '#e53935', W: '#ffffff', C: '#ffe0b2', K, M: '#c62828' },
    rows: [
      '....RRRR....',
      '..RRWWRRRR..',
      '.RRRWWRRWWR.',
      '.RRRRRRRWWR.',
      'RWWRRRRRRRRR',
      'RWWRRRRRRWWR',
      'RRRRRRRRRWWR',
      '..CCCCCCCC..',
      '..CCKCCKCC..',
      '..CCCCCCCC..',
      '..CCCMMCCC..',
      '...CCCCCC...',
    ],
  },
  robot: {
    name: 'Robot',
    palette: { G: '#b0bec5', D: '#607d8b', C: '#00e5ff', K, Y: '#ffd600' },
    rows: [
      '.....K......',
      '.....Y......',
      '..GGGGGGGG..',
      '.GGGGGGGGGG.',
      '.GCCGGGGCCG.',
      '.GCCGGGGCCG.',
      '.GGGGGGGGGG.',
      '.GGKKKKKKGG.',
      '..GGGGGGGG..',
      '.DDGGGGGGDD.',
      '..GGGGGGGG..',
      '..DD....DD..',
    ],
  },
  slime: {
    name: 'Slime',
    palette: { B: '#42a5f5', W: '#ffffff', K },
    rows: [
      '............',
      '............',
      '.....BB.....',
      '....BBBB....',
      '...BBBBBB...',
      '..BBBBBBBB..',
      '.BBWKBBBWKB.',
      '.BBBBBBBBBB.',
      '.BBBBKKBBBB.',
      '.BBBBBBBBBB.',
      '..BBBBBBBB..',
      '...BBBBBB...',
    ],
  },
  webHero: {
    name: 'Web hero',
    palette: { K, R: '#e53935', D: '#8e1b1b', W: '#ffffff' },
    rows: mirror([
      '........',
      '.....KKK',
      '...KKRRD',
      '..KRRDRD',
      '.KRRDRRD',
      '.KDDDDDD',
      'KRKKKRRD',
      'KKWWWKRD',
      'KKWWWWKD',
      'KRKWWWWK',
      'KRDKKKKD',
      '.KRRDRRD',
      '.KDDDDDD',
      '..KRRDRD',
      '...KKRRD',
      '.....KKK',
    ]),
  },
  nightHero: {
    name: 'Night hero',
    palette: { K, C: '#455a64', S: '#ffcc99', W: '#ffffff' },
    rows: mirror([
      '..K.....',
      '..KK....',
      '..KCK...',
      '..KCCKKK',
      '.KCCCCCC',
      '.KCCCCCC',
      '.KCCCCCC',
      '.KCWWWCC',
      '.KCCCCCC',
      '.KCCSSSS',
      '.KCSSSSS',
      '.KCSSSSS',
      '.KCSSSKK',
      '..KCSSSS',
      '...KKSSS',
      '.....KKK',
    ]),
  },
  greenGiant: {
    name: 'Green giant',
    palette: { K, H: '#263238', G: '#66bb6a', D: '#2e7d32', W: '#ffffff' },
    rows: mirror([
      '........',
      '...HHHHH',
      '..HHHHHH',
      '.HHHHHHH',
      '.HHGHHGH',
      '.HGGGGGG',
      '.KGDDGGG',
      '.KGGGDDG',
      '.KGWKGGG',
      '.KGGGGGD',
      '.KGGGGGG',
      '.KGGKKKK',
      '.KGGKWKW',
      '.KGGKKKK',
      '..KGGGGG',
      '...KKKKK',
    ]),
  },
  starShield: {
    name: 'Star shield',
    palette: { K, R: '#e53935', W: '#ffffff', B: '#1e63c6' },
    rows: mirror([
      '......KK',
      '....KKRR',
      '...KRRRR',
      '..KRRWWW',
      '.KRRWWRR',
      '.KRWWRBB',
      'KRRWRBBW',
      'KRWWRBWW',
      'KRWWRBBW',
      'KRRWRBWB',
      '.KRWWRBB',
      '.KRRWWRR',
      '..KRRWWW',
      '...KRRRR',
      '....KKRR',
      '......KK',
    ]),
  },
  armourHero: {
    name: 'Armour hero',
    palette: { K, R: '#c62828', Y: '#fbc02d', W: '#e0f7fa' },
    rows: mirror([
      '........',
      '....KKKK',
      '..KKRRRR',
      '.KRRRRRR',
      '.KRRYYYY',
      'KRRYYYYY',
      'KRYYYYYY',
      'KRYWWWYY',
      'KRYYWWYY',
      'KRRYYYYY',
      'KRRYYYYY',
      'KRRYYKKK',
      '.KRRYYYY',
      '.KRRRYYY',
      '..KRRRRR',
      '...KKKKK',
    ]),
  },
  thunderHammer: {
    name: 'Thunder hammer',
    palette: { K, G: '#b0bec5', D: '#78909c', B: '#8d6e63', L: '#5d4037', Y: '#ffd600' },
    rows: mirror([
      '........',
      '.KKKKKKK',
      '.KGGGGGG',
      '.KGDGGGG',
      '.KGGGGGG',
      '.KDDDDDD',
      '.KKKKKKK',
      '.Y....KB',
      '..Y...KL',
      '.Y....KB',
      '......KL',
      '......KB',
      '......KL',
      '......KB',
      '.....KLL',
      '......KK',
    ]),
  },
  blazeTop: {
    name: 'Blaze top',
    palette: { ...TOP_METAL, A: '#f4511e', L: '#ffab91', C: '#ffca28', G: '#b71c1c' },
    rows: BATTLE_TOP,
  },
  stormTop: {
    name: 'Storm top',
    palette: { ...TOP_METAL, A: '#1e88e5', L: '#90caf9', C: '#eceff1', G: '#00b8d4' },
    rows: BATTLE_TOP,
  },
  venomTop: {
    name: 'Venom top',
    palette: { ...TOP_METAL, A: '#8e24aa', L: '#ce93d8', C: '#76ff03', G: '#1b5e20' },
    rows: BATTLE_TOP,
  },
  goldTop: {
    name: 'Gold top',
    palette: { ...TOP_METAL, A: '#ffb300', L: '#ffe082', C: '#37474f', G: '#e53935' },
    rows: BATTLE_TOP,
  },
  blueSpeedster: {
    name: 'Blue speedster',
    palette: { K, B: '#1e63d6', W: '#ffffff', G: '#2e7d32', S: '#ffcc99' },
    rows: [
      '........KK......',
      '.......KBBK.....',
      '..KKKKKBBBBK....',
      '...KBBBBBBBBK...',
      'KKKBBBBBBBBBBK..',
      '.KBBBBBBBKWWWK..',
      '..KBBBBBBWWWGWK.',
      'KKBBBBBBBWWWKWK.',
      '.KBBBBBBBBWWWSKK',
      '..KBBBBBBBSSSSSK',
      '.KKBBBBBBSSSSSK.',
      'KBBBBBBBBBSKKSK.',
      '.KKBBBBBBBBSSK..',
      '...KBBBBBBBKK...',
      '....KKKKKKK.....',
      '................',
    ],
  },
  twinTailFox: {
    name: 'Twin-tail fox',
    palette: { K, O: '#fb8c00', W: '#ffffff', B: '#1565c0', P: '#ffab91' },
    rows: mirror([
      '.K......',
      '.KK.....',
      '.KOK....',
      '.KPOK...',
      '.KPOOKKK',
      '.KOOOOOO',
      'KOOOOOOO',
      'KOWWBOOO',
      'KOWBBOOO',
      'KOOWWWOO',
      'OKWWWWWK',
      'OOKWWWWW',
      'WOOKWWWW',
      'WWOOKKKK',
      '.WWOO...',
      '..WW....',
    ]),
  },
  redBrawler: {
    name: 'Red brawler',
    palette: { K, R: '#e53935', D: '#b71c1c', S: '#ffcc99', P: '#7b1fa2', W: '#ffffff' },
    rows: mirror([
      '....KKKK',
      '..KKRRRR',
      '.KRRRRRR',
      'KRRRRRRR',
      'KRRWWWRR',
      'KRRWPPRR',
      'KRRSSSSS',
      'KRSSSSSK',
      'KRSSSSSS',
      'KRRSSSKK',
      'KRRKSSSS',
      'KRDRKKKK',
      'KRKRK...',
      'KRKRK...',
      '.K.K....',
      '........',
    ]),
  },
  goldRing: {
    name: 'Gold ring',
    palette: { O: '#c79100', Y: '#fdd835', W: '#fff9c4' },
    rows: [
      '................',
      '.....OOOOOO.....',
      '...OOYYYYYYOO...',
      '..OOWWYYYYYYOO..',
      '..OWYYOOOOYYYO..',
      '.OWYYO....OYYYO.',
      '.OYYO......OYYO.',
      '.OYYO......OYYO.',
      '.OYYO......OYYO.',
      '.OYYO......OYYO.',
      '.OYYYO....OYYYO.',
      '..OYYYOOOOYYYO..',
      '..OOYYYYYYYYOO..',
      '...OOYYYYYYOO...',
      '.....OOOOOO.....',
      '................',
    ],
  },
  powerGem: {
    name: 'Power gem',
    palette: { K, G: '#43a047', L: '#a5d6a7', D: '#1b5e20', W: '#ffffff' },
    rows: mirror([
      '........',
      '........',
      '...KKKKK',
      '..KLWLLG',
      '.KLLLLGG',
      'KDDDDDDD',
      'KGGGDGGG',
      '.KGGDGGG',
      '..KGGDGG',
      '...KGDGG',
      '....KGDG',
      '.....KGD',
      '......KG',
      '.......K',
      '........',
      '........',
    ]),
  },
  catchBall: {
    name: 'Catch ball',
    palette: { K, R: '#e53935', W: '#ffffff' },
    rows: [
      '......KKKK......',
      '....KKRRRRKK....',
      '...KRWWRRRRRK...',
      '..KRWWRRRRRRRK..',
      '.KRWRRRRRRRRRRK.',
      '.KRRRRRKKRRRRRK.',
      'KRRRRRKWWKRRRRRK',
      'KKKKKKWWWWKKKKKK',
      'KKKKKKWWWWKKKKKK',
      'KWWWWWKWWKWWWWWK',
      '.KWWWWWKKWWWWWK.',
      '.KWWWWWWWWWWWWK.',
      '..KWWWWWWWWWWK..',
      '...KWWWWWWWWK...',
      '....KKWWWWKK....',
      '......KKKK......',
    ],
  },
  bulbBuddy: {
    name: 'Bulb buddy',
    palette: { K, T: '#4db6ac', D: '#00897b', G: '#66bb6a', E: '#2e7d32', R: '#e53935', W: '#ffffff' },
    rows: mirror([
      '......KK',
      '....KKGG',
      '...KGGGE',
      '..KGGGEG',
      'K.KEGGEG',
      'KTKKKKKK',
      'KTTTTDTT',
      'KTTTTTTT',
      'KTWRTTTT',
      'KTKRTTTT',
      'KDTTTTTT',
      'KTTTTTKK',
      '.KTTTTTT',
      '.KTDTTTT',
      '.KTTKTTT',
      '..KKKKKK',
    ]),
  },
  bubbleTurtle: {
    name: 'Bubble turtle',
    palette: { K, B: '#4fc3f7', W: '#ffffff', S: '#8d6e63', C: '#fff3c4' },
    rows: mirror([
      '....KKKK',
      '...KBBBB',
      '..KBBBBB',
      '..KBWKBB',
      '..KBWKBB',
      '..KBBKBB',
      '...KBBKK',
      '....KKKK',
      '.KKKSCCC',
      'KBBKSCCC',
      '.KKKSSSS',
      '...KSCCC',
      '...KSSSS',
      '..KBKCCC',
      '..KBBKKK',
      '...KK...',
    ]),
  },
  puffball: {
    name: 'Puffball',
    palette: { K, P: '#f8bbd0', W: '#ffffff', B: '#1e88e5', D: '#f06292' },
    rows: mirror([
      '........',
      '.KK..KKK',
      '.KPKKPPP',
      '.KPPPPPP',
      'KPPPPPPP',
      'KPWWWPPP',
      'KWWBBWPP',
      'KWBBKWPP',
      'KWBBBWPP',
      'KPWWWPPP',
      'KPPPPPPK',
      'KPPDPPPP',
      '.KPPPPPP',
      '..KPPPPP',
      '...KKKKK',
      '........',
    ]),
  },
  grinGhost: {
    name: 'Grin ghost',
    palette: { K, U: '#7e57c2', R: '#ff1744', W: '#ffffff' },
    rows: mirror([
      '.K...K..',
      '.KK.KUK.',
      '.KUKUUUK',
      '.KUUUUUU',
      'KUUUUUUU',
      'KUURUUUU',
      'KUURRUUU',
      'KUUUUUUU',
      'KUKKKKKK',
      'KUKWKWKW',
      'KUUKWWWW',
      'KUUUKKKK',
      '.KUUUUUU',
      '..KUUUUU',
      '.KUUKKKK',
      '.KKK....',
    ]),
  },
  greenCap: {
    name: 'Green cap hero',
    palette: { R: '#43a047', H: '#5d4037', S: '#ffcc99', K, M: '#c62828', B: '#283593', W: '#ffffff' },
    rows: CAP_HERO,
  },
  powerStar: {
    name: 'Power star',
    palette: { K, O: '#e6a100', Y: '#fdd835' },
    rows: mirror([
      '........',
      '.......O',
      '......OY',
      '......OY',
      '.....OYY',
      'OOOOOOYY',
      'OYYYYYYY',
      '.OYYYKYY',
      '..OYYKYY',
      '...OYYYY',
      '...OYYYY',
      '..OYYYYY',
      '..OYYYOO',
      '.OYYOO..',
      '.OOO....',
      '........',
    ]),
  },
  coin: {
    name: 'Coin',
    palette: { O: '#b8860b', Y: '#ffd54f', S: '#f9a825', W: '#fff8e1' },
    rows: [
      '................',
      '.....OOOOOO.....',
      '....OYYYYYYO....',
      '...OYWYYYYYYO...',
      '...OYWYSSYYYO...',
      '..OYWYYSSYYYYO..',
      '..OYWYYSSYYYYO..',
      '..OYYYYSSYYYYO..',
      '..OYYYYSSYYYYO..',
      '..OYYYYSSYYYYO..',
      '..OYYYYSSYYYYO..',
      '...OYYYSSYYYO...',
      '...OYYYYYYYYO...',
      '....OYYYYYYO....',
      '.....OOOOOO.....',
      '................',
    ],
  },
  questionBlock: {
    name: 'Question block',
    palette: { B: '#8d4a00', Y: '#fbc02d', D: '#c77800', W: '#ffffff' },
    rows: [
      '.BBBBBBBBBBBBBB.',
      'BYYYYYYYYYYYYYYB',
      'BYDYYWWWWWYYYDYB',
      'BYYYWWDDDWWYYYYB',
      'BYYYWWDYYWWDYYYB',
      'BYYYYDDYYWWDYYYB',
      'BYYYYYYYWWDDYYYB',
      'BYYYYYYWWDDYYYYB',
      'BYYYYYYWWDYYYYYB',
      'BYYYYYYYDDYYYYYB',
      'BYYYYYYWWYYYYYYB',
      'BYYYYYYWWDYYYYYB',
      'BYYYYYYYDDYYYYYB',
      'BYDYYYYYYYYYYDYB',
      'BYYYYYYYYYYYYYYB',
      '.BBBBBBBBBBBBBB.',
    ],
  },
  fireFlower: {
    name: 'Fire flower',
    palette: { K, R: '#e53935', O: '#fb8c00', Y: '#fff176', W: '#ffffff', G: '#43a047', D: '#2e7d32' },
    rows: mirror([
      '....KKKK',
      '..KKRRRR',
      '.KRROOOO',
      'KRROYYYY',
      'KROYWWWW',
      'KROYWKWW',
      'KRROYYYY',
      '.KRROOOO',
      '..KKRRRR',
      '....KKKG',
      '.KK...KG',
      'KGGK..KG',
      'KGDGK.KG',
      '.KGDGKKG',
      '..KGGGGG',
      '...KKKKK',
    ]),
  },
  greenPipe: {
    name: 'Green pipe',
    palette: { K, G: '#43a047', L: '#a5d6a7', D: '#1b5e20' },
    rows: [
      'KKKKKKKKKKKKKKKK',
      ...Array<string>(3).fill('KLLGGGGGGGGGGDDK'),
      'KKKKKKKKKKKKKKKK',
      ...Array<string>(11).fill('.KLLGGGGGGGGDDK.'),
    ],
  },
};

export function isSprite(value: string): boolean {
  return value.startsWith(SPRITE_PREFIX) && SPRITES[value.slice(SPRITE_PREFIX.length)] !== undefined;
}

export function spriteName(value: string): string {
  return SPRITES[value.slice(SPRITE_PREFIX.length)]?.name ?? value;
}

// Sprites are square, so the row count is the size.
export function spriteSize(value: string): number {
  return SPRITES[value.slice(SPRITE_PREFIX.length)]?.rows.length ?? 0;
}

export function spritePixels(value: string): Pixel[] {
  const sprite = SPRITES[value.slice(SPRITE_PREFIX.length)];
  if (!sprite) return [];
  const pixels: Pixel[] = [];
  sprite.rows.forEach((row, y) => {
    [...row].forEach((ch, x) => {
      const c = sprite.palette[ch];
      if (c) pixels.push({ x, y, c });
    });
  });
  return pixels;
}

export const SPRITE_VALUES = Object.keys(SPRITES).map((k) => SPRITE_PREFIX + k);
